### ISSUE TITLE
won't compile

### ISSUE THREAD

**Issue by geoffrey-young** [PLG/ZeroMQ-Framework#4]
hi there.

I can't get the framework to compile - it complains about platform.hpp not being found (even though it's there, of course).  are there some missing linker flags I need to add?

I'm also a bit confused about how to go about getting the framework into the state where it can be used.  I'm assuming I need to first compile it, and that the ZeroMQ-iOS.framework file will be created as a result...  

I'm using the same versions of Xcode, zmq, etc you list.

thanks :)

**Comment by PLG** [comment]
Hi !

Did you add the submodules?

If you look at Paolo's blog... 1st step... you have to prepare zmq. I have prepared it for my system and imported that into the framework. However, your system might be different, so you can go through that step and then import the platform.hpp

There are compiled frameworks under "releases", you can try. 

Yes, if you compile you get the framework directory structure as a result.
Cheers!
