### ISSUE TITLE
linker errors when building ZeroMQ-framework

### ISSUE THREAD

**Issue by dmanrke** [PLG/ZeroMQ-Framework#5]
hi Gents,

i followed same steps and trying to generate zmq universial framework for ios (ios 6 - 7). there is no error at the time of building framework. but when i use this framework in to another static libtary getting errors (linkers) .. 

i am putting here one of several error - 

Undefined symbols for architecture i386:
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::find(char const_, unsigned long, unsigned long) const", referenced from:
      zmq::socket_base_t::parse_uri(char const_, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in ZeroMQ-IOS(socket_base.o)
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::compare(char const_) const", referenced from:
      zmq::socket_base_t::check_protocol(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in ZeroMQ-IOS(socket_base.o)
      zmq::socket_base_t::bind(char const_) in ZeroMQ-IOS(socket_base.o)
      zmq::socket_base_t::connect(char const_) in ZeroMQ-IOS(socket_base.o)
      zmq::socket_base_t::term_endpoint(char const_) in ZeroMQ-IOS(socket_base.o)
      zmq::socket_base_t::monitor(char const_, int) in ZeroMQ-IOS(socket_base.o)
      zmq::tcp_address_t::resolve(char const_, bool, bool) in ZeroMQ-IOS(tcp_address.o)
      zmq::tcp_address_mask_t::resolve(char const*, bool) in ZeroMQ-IOS(tcp_address.o)
      ...

please give me some clarification about how can i build this framework (Universial)

Thanks in advanced ...

**Comment by PLG** [comment]
My first guess would be that you aren't importing the base iOS libraries anywhere. You haven't really provided much information to guess otherwise. You can find a pre-built universal library under the releases section.
