### ISSUE TITLE
unknown type name ZMQContext 

### ISSUE THREAD

**Issue by DevGW** [PLG/ZeroMQ-Framework#6]
I have compiled and build the framework and included it into an ios project and this line gives error:

ZMQContext *ctx = [[ZMQContext alloc] initWithIOThreads:1U];

any suggestions?  not sure if this is an issue with my build of the framework or what.

**Comment by PLG** [comment]
Most likely what is stated at the bottom of the README. That the header files didn't get copied correctly.
