### ISSUE TITLE
Are you using the normal C functions vs Objective C methods

### ISSUE THREAD

**Issue by richtong** [PLG/ZeroMQ-Framework#7]
Just a little confused, it looks like this project isn't an effort to make ZeroMQ look like an Objective C class and provide methods over it. Instead, you call C function directly right?

**Comment by PLG** [comment]
Yes, that is correct. This just ports the libraries onto iOS devices. Obj-C wrappers exist already, anyhow if you prefer.  You could recompile the framework for yourself to include an Obj-C wrapper if you like. Cheers!

**Comment by richtong** [comment]
Oh. Thanks. Do u know what build has these. The only one I saw does objective c but only for OS X and not for iOS. Google hasn't been my friend here. 

Thanks,
Rich

Sent from my iPhone

It will be all right in the end. And if it is not all right then it must not yet be the end. Sonny Kapur. The Best Exotic Marigold Hotel. 2011. 

+1-206-963-9029 | @richtong | Fb.me/richtong1 | tongfamily.com 
| igncap.com | +86-137-6184-9029 | qimingvc.com

**Comment by PLG** [comment]
I'm sorry. I misunderstand you. As said in my previous message. The framework is for iOS. Build? You can find the build numbers on the README and releases page. Success.
